name 'optoro_rabbitmq'
maintainer 'Optoro'
maintainer_email 'devops@optoro.com'
license 'MIT'
description 'Installs/Configures a single instance of rabbitmq server'
long_description 'Installs/Configures a single rabbitmq service node based on the provided configuration.'
version '0.2.3'

depends 'optoro_monit'
depends 'rabbitmq'
depends 'optoro_metrics'
