name 'optoro_rabbitmq'
maintainer 'Optoro'
maintainer_email 'devops@optoro.com'
license 'All rights reserved'
description 'Installs/Configures optoro_rabbitmq'
long_description 'Installs/Configures optoro_rabbitmq'
version '0.2.0'

depends 'optoro_monit'
depends 'rabbitmq'
